name: Create Java Release Workflow

on:
  workflow_call:
    inputs:
      workingDirectory:
        required: false
        type: string
        default: '.'
      javaVersion:
        required: false
        type: string
        default: '21'
      dockerSupport:
        required: false
        type: boolean
        default: false
      generateRelease:
        required: false
        type: boolean
        default: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workingDirectory }}
    steps:
      - uses: actions/checkout@v7
      - name: Verify version against tag
        uses: nimbox/build-tools/actions/verify-version@main
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.javaVersion }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Setup Docker (Optional)
        if: ${{ inputs.dockerSupport }}
        uses: docker/setup-buildx-action@v4
      - name: Authenticate with private NPM packages
        run: |
          echo "@nimbox:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NIMBOX_PUBLISH_TOKEN }}" >> ~/.npmrc
      - name: Build Gradle
        run: ./gradlew build
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.NIMBOX_PUBLISH_TOKEN }}
      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.NIMBOX_PUBLISH_TOKEN }}
  create-release:
    needs: build-and-publish
    if: ${{ inputs.generateRelease }}
    uses: nimbox/build-tools/.github/workflows/create-release.yaml@main
    secrets: inherit
