name: Java Build Workflow

on:
  workflow_call:
    inputs:
      workingDirectory:
        required: false
        type: string
        default: '.'
      javaVersion:
        required: false
        type: string
        default: '21'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workingDirectory }}
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.javaVersion }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Authenticate with private NPM packages
        run: |
          echo "@nimbox:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NIMBOX_PUBLISH_TOKEN }}" >> ~/.npmrc
      - name: Build and test
        run: ./gradlew build
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.NIMBOX_PUBLISH_TOKEN }}
